config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'

  resources :questions, except: [:update] do
    resources :answers
    post "/answers/:id", to: 'answers#update'
  end

  get "/search", to: "questions#search"
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  validates :body, presence: true

  belongs_to :question
  belongs_to :user
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  validates :title, presence: true, length: { maximum: 100 }
  validates :body, presence: true

  has_many :answers
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :authenticate_user!

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params)
    redirect_to question_path(@question)
  end

  def destroy
    id = params['id']
    Answer.destroy(id)
    redirect_to question_path(params['question_id']), notice: 'Answer deleted'
  end

  def update
    id = params['id']
    counter = params['counter']

    if counter == 'up'
      Answer.find(id).increment!(:votes)
    else
      Answer.find(id).decrement!(:votes)
    end

    redirect_to question_path(params['question_id'])
  end

  private

  def answer_params
    permitted = params.require(:answer).permit(:body)
    permitted.merge({ user_id: current_user.id })
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    render
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!

  def new
    @question = Question.new
  end

  def create
    permitted_params = params.require(:question).permit(:title, :body)
    params = permitted_params.merge({ user_id: current_user.id, votes: 0 })
    question = Question.new(params)

    if question.save
      redirect_to '/'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @questions = Question.order(created_at: :desc)
  end

  def show
    id = params['id']
    @question = Question.find(id)
    @question_answers = @question.answers.order(votes: :desc, created_at: :desc)
  end

  def destroy
    id = params['id']
    Question.destroy(id)
    redirect_to questions_path, notice: 'Question deleted'
  end

  def search
    if params[:search].empty?
      redirect_to questions_path
    else
      key = "%#{params[:search]}%"
      @questions = Question.where('title LIKE :search OR body LIKE :search', search: key).order(votes: :desc,
                                                                                                created_at: :desc)
      render template: 'questions/index'
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
  <h1> A place to ask questions! </h1>
  <%= button_to "Ask question", new_question_path, method: :get %>

  <br>
  <hr>
  <%= button_to "All questions", questions_path, method: :get %>

<%else%>
  <%= link_to "Sign in", new_user_session_path %>
<%end%>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
  <%= button_to "Home", "/", method: :get %>
  <h3> <%="Welcome #{current_user.email}!"%> </h3>
<%end%>
<hr>

app/views/layouts/_questions.html.erb
<ul>
  <% @questions.each do |question| %>
    <li>
      <a href="<%= question_path(question) %>">
        <%= question.title %>
      </a>
    </li>
  <% end %>
</ul>

app/views/layouts/_search.html.erb
<hr>
<%= form_tag(search_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag("Search") %>
<% end %>
<%= button_to "Clear", questions_path, method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zquestions</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csrf_meta_tag %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<h1>Questions</h1>

<%= render "layouts/search" %>
<%= render "layouts/questions" %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= form_with model: @question do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<p><%= @question.body %></p>

<% if current_user.id == @question.user_id%>
  <%= button_to "Delete question", question_path(@question), method: :delete %>
<%end%>

<h2>Answers</h2>
<% @question_answers.each do |answer| %>
  <hr>
  <p> <%=answer.created_at%> </p>
  <p> Approval: <%=answer.votes%> </p>
  <%= button_to question_answer_path([answer.question, answer], counter: :up, id: answer.id), method: :patch do %>
    <i class="fa-solid fa-thumbs-up"></i>
  <%end%>
  <%= button_to question_answer_path([answer.question, answer], counter: :down, id: answer.id), method: :patch do %>
    <i class="fa-solid fa-thumbs-down"></i>
  <%end%>
  <p>
    <strong><%= answer.user.email %>:</strong>
    <%= answer.body %>
    <% if current_user.id == answer.user_id%>
      <%= button_to "Delete", [answer.question, answer], method: :delete %>
    <%end%>
  </p>
  </hr>
<% end %>

<%= form_with model: [ @question, @question.answers.build ] do |form| %>
  <p>
    <%= form.label 'Answer' %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit "Submit answer" %>
  </p>
<% end %>